import "./globals.css";

import { css } from "@flows/styled-system/css";
import { Providers } from "components/providers";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts -- needed for noflash script */}
        <script src="/noflash.min.js" />
      </head>
      <body className={css({ background: "bg" })}>
        <Providers>{children}</Providers>
      </body>
      <Script
        data-api="https://flows.sh/box/event"
        data-domain="app.flows.sh"
        defer
        src="https://flows.sh/box/script.js"
      />
    </html>
  );
}
